schema_version = "1.0.0"
id = "cyn_texture_encoder"
version = "0.1.0"
name = "Texture Encoder"
tagline = "Encode arbitrary vertex data to a texture"
maintainer = "Coralynn Colombe <coralynn@cyn.sh>"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2024 Coralynn Colombe",
]

# wheels = [
# ]

# [permissions]
# network = "Need to sync motion-capture data to server"
# files = "Import/export FBX from/to disk"
# clipboard = "Copy and paste bone transforms"
